# Generated by Django 4.1.2 on 2022-10-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0002_rename_movies_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(),
        ),
    ]
